controller_list:
  - name: j2n6s300_driver/joints_action
    action_ns: joint_angles
    type: ArmJointAngles
    default: true
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
  - name: j2n6s300_driver/fingers_action
    action_ns: finger_positions
    type: kinova_msgs/SetFingersPosition
    default: true    
    joints:
      - j2n6s200_joint_finger_1
      - j2n6s200_joint_finger_2

